//   في الويب كله render اول ملف بيتعمله 
import Navbar from "@/Components/Navbar/Navbar";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";

export const metadata = {
  title: "JO Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <ThemeProvider>
          <Navbar />
          <main className="main">
            <section className="main-section">{children}</section>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
